---
- name: Install nginx
  apt: 
    name: nginx 
    state: latest

- name: Start and enable service
  service:
    name: nginx
    state: started

- name: Copy Test Page
  copy: 
    src: index_page/
    dest: /var/www/html
